name: Build and deploy ASP.Net Core app to Azure Web App - webdot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore src/Web/Web.csproj

      - name: Build with dotnet
        run: dotnet build src/Web/Web.csproj --configuration Release

      - name: Publish
        run: dotnet publish src/Web/Web.csproj -c Release -f net8.0 -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_38C92D54306040FB910FC717EE04B018 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5145872007D746C2B3E750DBE0E8D722 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_486F6A777B3C4C22A6F23C7F5502E8F3 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'webdot'
          slot-name: 'Production'
          package: .
